---
title: "AC Reviews and Meta-analyses"
author: "Lindsey Thurman"
date: "March 4, 2017"
output: html_document
---
Proportion of reviews and meta-analyses on species adaptive capacity to climate change by AC mechanism, system, and/or taxa. Follow the breadcrumbs (concentric pie slices) to uncover these hierarchical relationships.  

```{r echo=FALSE, include=FALSE}
REVIEWS<-read.csv("AC Reviews & Meta-analyses.csv", header=T)

library(rmarkdown)
library(sunburstR)
library(dplyr)
library(TraMineR)
library(pipeR)

REVIEWS.seq <- seqdef(REVIEWS, 3:5)

REVIEWS.seqtab<-seqtab( seqdss(REVIEWS.seq), tlim = 0, format = "SPS" ) %>>%
  attr("freq") %>>%
  (
    data.frame(
      # appending "-end" is necessary for this to work
      sequence = paste0(
        gsub(
          x = names(.$Freq)
          , pattern = "(/[0-9]*)"
          , replacement = ""
          , perl = T
        )
        #,"-end"
      )
      ,freq = as.numeric(.$Freq)
      ,stringsAsFactors = FALSE
    )
  ) 
  sunburst<-sunburst(count=TRUE, REVIEWS.seqtab)


```


```{r echo=FALSE}
htmlwidgets::onRender(
  sunburst(REVIEWS.seqtab, count=TRUE),
  '
function(el,x){
  d3.select(el).select(".sunburst-sidebar").remove()
}
  '
)
#saveWidget(sunburst, "sunburstv1.html", selfcontained = TRUE,
 # background = "white")
```
<br>
<br>
<br>
<br>
Condensed by AC Mechanism:
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)

REVIEWS.seq2 <- seqdef(REVIEWS, 3)
REVIEWS.seq2$value <- rep(1, nrow(REVIEWS.seq2))

p <- plot_ly() %>%
  add_pie(data = count(REVIEWS.seq2, AC_Mechanisms), labels = ~AC_Mechanisms, values = ~n, name = "AC Mechanisms")%>%
  layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
p
```

